const bcrypt = require("bcryptjs");

const data = {
  users: [
    {
      name: 'san',
      email: 'junbuck@gmail.com',
      password: bcrypt.hashSync('1214', 8),
      isSeller:true,
      isAdmin: true,
      seller: {
        name: 'san',
        logo: '/images/p2.jpg',
        description: '강산',
        rating: 4.5,
        numReviews: 120,
      },
    },
    {
      name: 'kang',
      email: 'junbuc@naver.com',
      password: bcrypt.hashSync('1214', 8),
      isSeller: true,
      isAdmin: false,
      seller: {
        name: 'kang',
        logo: '/images/p1.jpg',
        description: '강산',
        rating: 4.5,
        numReviews: 120,
      },
    },
  ],
  products: [
    {
      name: '나이키 슬림 셔츠',
      category: '셔츠',
      image: '/images/p1.jpg',
      price: 12000,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: '나이키 슬림셔츠는 하이퀄리티 셔츠입니다.',
    },
    {
      name: '아디다스 핏 셔츠',
      category: '셔츠',
      image: '/images/p2.jpg',
      price: 10000,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: '하이 퀄리티 셔츠입니다.',
    },
    {
      name: '라코스테 프리 셔츠',
      category: '셔츠',
      image: '/images/p3.jpg',
      price: 22000,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: '하이 퀄리티 상품입니다',
    },
    {
      name: '나이키 슬림 바지',
      category: '바지',
      image: '/images/p4.jpg',
      price: 78000,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: '하이퀄리티 바지입니다.',
    },
    {
      name: '푸마 슬림 바지',
      category: '바지',
      image: '/images/p5.jpg',
      price: 65000,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: '하이퀄리티 슬림 바지 입니다.',
    },
    {
      name: '아디다스 슬림 바지',
      category: '바지',
      image: '/images/p6.jpg',
      price: 139000,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: '하이퀄리티 상품입니다.',
    },
  ],
};
module.exports= data;